# Basic `dependabot.yml` file with
# minimum configuration for Python

version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    # Look for `requirements.txt` in the `root` directory
    directory: "/"
    # Check the Python package index (PyPI) for updates every day (weekdays)
    schedule:
      interval: "daily"
