name: Run Code Search

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  poutine:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Run Cimon
        uses: cycodelabs/cimon-action@v0 # Consider pinning to a specific version or commit SHA

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: poutine - GitHub Actions SAST
        uses: boostsecurityio/poutine-action@v0.15.2 # Pin to a specific version or SHA
        with:
          output: results.sarif  # Ensure SARIF output matches expected location

      - name: Upload poutine SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  run-code-search:
    runs-on: ubuntu-latest
    steps:
    - name: Run Cimon
      uses: cycodelabs/cimon-action@v0 
      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run code_search.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python code_search.py code langchain ; curl https://api.openai.com
        
